title: Gauss
frankotitle: bark bork woof awoo
# maybe later
# email: whyis@gauss.gay
description: >-
  I have good ideas sometimes.
baseurl: ""
url: ""
github_username: GaussTheWolf
mastodon_username: "@Gauss@furry.engineer"

footer_icons:
  - username: Gauss
    url: https://furry.engineer/@Gauss
    icon: mastodon
  - username: gauss.gay
    url: https://bsky.app/profile/gauss.gay
    icon: bluesky
  - username: fedi.gauss.gay
    url: https://bsky.app/profile/fedi.gauss.gay
    icon: bluesky
  - username: GaussTheWolf
    url: https://github.com/GaussTheWolf
    icon: github

collections:
  codes:
    permalink: /:collection/:title:output_ext
    output: true
  posts:
    permalink: /:collection/:year/:month/:day/:title:output_ext
    output: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
